// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ykdskdmujtwnuwhwzerm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlrZHNrZG11anR3bnV3aHd6ZXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTMzMjEsImV4cCI6MjA2NDQ2OTMyMX0.rw2mmkSqk1A7nEe7xUpX78s83duCLdAFLVYpAoKN8Wk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);